title: Julián López - Data Scientist
description: Professional project portfolio.
theme: minima

# Configuración adicional
author: Julián Camilo López Sánchez
email: jclopezs@uniandes.edu.co
social:
  - icon: "fab fa-linkedin"
    link: "https://www.linkedin.com/in/your-profile"
  - icon: "fab fa-kaggle"
    link: "https://www.kaggle.com/your-profile"
